
server:
  port: 80
#活动配置，当前使用配置，最上端为默认配置
#spring:
#  profiles:
#    active: local
#---三条杠作为分割线
spring:
  thymeleaf:
    cache: false
---
server:
  port: 8080
#当前配置名称
spring:
  profiles: local
---
server:
  port: 8090
spring:
  profiles: test