server:
  port: 81
spring:
  datasource:
    url: jdbc:mysql://47.97.25.40:3306/grey_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: blue
    password: z0420
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
